# Sourced by /usr/local/bin/musl-clang in PHP debug images.
MUSL_CLANG_SANITIZE_CXX=address
MUSL_CLANG_COMPILE_FLAGS=(
    -fsanitize=address,undefined
    -fno-sanitize=function
)
MUSL_CLANG_LINK_FLAGS=(
    -fsanitize=address,undefined
    -fno-sanitize=function
)
